project:  
  type: website
  output-dir: ./docs/english
website:  
  title: "Jakub Štenc"
  navbar: 
    logo: "images/pyl.png"
    right: 
      - text: "English"
        href: ../english/index.html
      - text: "Česky"
        href: ../czech/index.html  
      
format: 
  html:
    theme: sandstone
    toc: true
